version: '2'

services:
  mysql:
    image: mysql
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "testdb"
    ports:
      - 3306:3306

  spring-boot-app:
    image: demo-spring-boot
    container_name: demo-spring-boot
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "testdb"
    ports:
      - 8081:8080
